### ISSUE TITLE
Error when pressing upload

### ISSUE THREAD

**Issue by GoogleCodeExporter** [danielgalassi/analytics-validator-service#1]
```
What steps will reproduce the problem?
1. Browse the attached XUDML
2. Press the upload button

What is the expected output? What do you see instead?
I get the attached.

What version of the product are you using? On what operating system?
I am using windows 7, Tomcat 7.0.53, firefox 26

Please provide any additional information below.


```

Original issue reported on code.google.com by `dimitris...@gmail.com` on 10 Apr 2014 at 12:01

Attachments:
- [hr_test_report_BI0046.txt](https://storage.googleapis.com/google-code-attachments/analytics-validator-service/issue-1/comment-0/hr_test_report_BI0046.txt)
- [obiee validator error.jpg](https://storage.googleapis.com/google-code-attachments/analytics-validator-service/issue-1/comment-0/obiee validator error.jpg)

**Comment by danielgalassi** [comment]
Fixed.
